spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: openai-plugin

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update


open-ai:
  base-url: ${BASE_URL}
  key: ${API_KEY}
  simulate: true
  connection-timeout: 10000
  read-timeout: 10000